version: "3.8"

services:
  hackathon-health-fusion:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - WATCH_MODE=${WATCH_MODE}
    ports:
      - "3000:3000"

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: health_fusion
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
