services:
  hackathon-health-fusion:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - WATCH_FILES=${WATCH_FILES}
    # ports:
    #   - "3000:3000"
    # expose:
    #   - "3000"
    volumes:
      - .:/app
