services:
  hackathon-health-fusion:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - WATCH_MODE=${WATCH_MODE}
    ports:
      - "3000:3000"
    expose:
      - "3000"
    volumes:
      - .:/app
